### ISSUE TITLE
GPL-v3-or-later license on new files is incompatible with GPL-v2-only license of some existing QEMU files

### ISSUE THREAD

**Issue by pm215** [eurecom-s3/symqemu#2]
Hi; it looks like you've licensed the new files you've added as GPL-v3-or-later (eg accel/tcg/tcg-runtime-sym.c). Unfortunately the GPLv3 is not compatible with the GPLv2, and some existing parts of QEMU are licensed as GPLv2-only (not v2-or-later) (eg util/qemu-sockets.c).

I'm guessing this was unintentional -- the easiest fix would be for you to relicense the code you've added as GPL-v2-or-later.

**Comment by sebastianpoeplau** [comment]
Hi, thanks for pointing out that issue! I guess we'll do what you suggested...
