### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by pythononedog** [eurecom-s3/symqemu#28]
../configure --disable-werror --enable-system --symcc-source=/home/ubuntu/symcc --symcc-build=/home/ubuntu/symcc/build
make

**error:**
ubuntu@ubuntu-B365-N:~/symqemu/build$ make
  GEN     docs/version.texi
  GEN     qemu-doc.html
  GEN     qemu-doc.txt
  GEN     docs/interop/qemu-qmp-ref.html
  GEN     docs/interop/qemu-qmp-ref.txt
  GEN     docs/interop/qemu-ga-ref.html
  GEN     docs/interop/qemu-ga-ref.txt
  CC      block.o
  LINK    qemu-nbd
  LINK    qemu-img
  LINK    qemu-io
  GEN     aarch64-softmmu/config-devices.h
  GEN     aarch64-softmmu/config-target.h
  GEN     trace/generated-helpers.c
/home/ubuntu/symqemu/scripts/tracetool/__init__.py:456: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(format) is 0:
/home/ubuntu/symqemu/scripts/tracetool/__init__.py:461: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(backends) is 0:
  LINK    aarch64-softmmu/symqemu-system-aarch64
  GEN     alpha-softmmu/config-devices.h
  GEN     alpha-softmmu/config-target.h
  CC      alpha-softmmu/tcg/tcg.o
In file included from /usr/include/sched.h:29,
                 from /usr/include/pthread.h:22,
                 from /usr/include/glib-2.0/glib/deprecated/gthread.h:124,
                 from /usr/include/glib-2.0/glib.h:112,
                 from /home/ubuntu/symqemu/include/glib-compat.h:32,
                 from /home/ubuntu/symqemu/include/qemu/osdep.h:140,
                 from /home/ubuntu/symqemu/tcg/tcg.c:28:
/home/ubuntu/symqemu/tcg/tcg.c: In function ‘tcg_context_init’:
/home/ubuntu/symqemu/tcg/tcg.c:1000:9: error: ‘ArchCPU’ {aka ‘AlphaCPU’} has no member named ‘env_exprs’
 1000 |         offsetof(ArchCPU, env_exprs) - offsetof(ArchCPU, env), "env");
      |         ^~~~~~~~
make[1]: *** [/home/ubuntu/symqemu/rules.mak:69: tcg/tcg.o] Error 1
make: *** [Makefile:472: alpha-softmmu/all] Error 2

**Comment by aurelf** [comment]
It seems that you tried to compile SymQEMU for the alpha guest architecture, this is not supported for now. I imagine this is not what you were looking for. That would not happen if you follow the sample instructions in the README.
