### ISSUE TITLE
Segmentation fault when commenting a tcgv_i64_expr_num

### ISSUE THREAD

**Issue by carolynsala585** [eurecom-s3/symqemu#29]
As far as I know, if I comment the [lines 4-5](https://github.com/eurecom-s3/symqemu/blob/master/tcg/tcg-op.h#L573-L574), 

```c
1. static inline void tcg_gen_mov_i64(TCGv_i64 ret, TCGv_i64 arg)
2. {
3.     if (ret != arg) {
4.         tcg_gen_op2_i64(INDEX_op_mov_i64, tcgv_i64_expr_num(ret),
5.                         tcgv_i64_expr_num(arg));
6.         tcg_gen_op2_i64(INDEX_op_mov_i64, ret, arg);
7.     }
8. }
```

the Qemu shouldn't crash, but I would get the wrong result from symqemu instead.  but I got the segmentation fault message :

```bash
echo test | x86_64-linux-user/symqemu-x86_64 ./a.out 
This is SymCC running with the QSYM backend
/........./symqemu/tcg/tcg.c:3312: tcg fatal error
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[1]    91043 done                              echo test | 
       91044 segmentation fault (core dumped)  x86_64-linux-user/symqemu-x86_64 ./a.out
```

Would appreciate if you could provide me with some guidance on how I can enable/disable some parts of the TCG generation in Symqemu.

**Comment by aurelf** [comment]
Thanks for your interest, and for your question.  Sorry for the late response. 

Not very clear what you want to do. I think here you are removing all the generated code, so the resulting binary is invalid. 
If you are still interested in this problem, please reopen the bug with a minimal test case. Ideally with asm output of what is generated and what you would like to achieve in comparison. That would help to understand.
