### ISSUE TITLE
Support for target riscv64-linux-user

### ISSUE THREAD

**Issue by natrhythm** [eurecom-s3/symqemu#35]
I get the following error when compiling symqemu for `--target-list=x86_64-linux-user`:

> 
>   CC      riscv64-linux-user/tcg/tcg.o
> In file included from /usr/include/sched.h:29,
>                  from /usr/include/pthread.h:22,
>                  from /usr/include/glib-2.0/glib/deprecated/gthread.h:124,
>                  from /usr/include/glib-2.0/glib.h:111,
>                  from /symqemu/include/glib-compat.h:32,
>                  from /symqemu/include/qemu/osdep.h:140,
>                  from /symqemu/tcg/tcg.c:28:
> /symqemu/tcg/tcg.c: In function 'tcg_context_init':
> /symqemu/tcg/tcg.c:1000:9: error: 'ArchCPU' {aka 'RISCVCPU'} has no member named 'env_exprs'
>  1000 |         offsetof(ArchCPU, env_exprs) - offsetof(ArchCPU, env), "env");
>       |         ^~~~~~~~
> make[1]: *** [/symqemu/rules.mak:69: tcg/tcg.o] Error 1
> make: *** [Makefile:472: riscv64-linux-user/all] Error 2
> 
> 

Flex and Bison are installed, and all Qemu dependencies are installed with `apt build-dep qemu`.

**Comment by aurelf** [comment]
Hi, 
can you post more information? Complete log (including configure logs), all comands (configure, make  etc), OS version and platform? 

Thanks

**Comment by aurelf** [comment]
Thanks, for now the target riscv64-linux-user isn't supported. 
The changes are probably quite minimal (adding the symbolic state for riscV cpu structure) . 
It would be nice if you provide a PR for this (if you don't there are chances we do soon anyway). 
Note, that we will soon push a port os SymQEMU to QEMU8. 
That change will be needed there too and porting it should be simple I think.

**Comment by aurelf** [comment]
In the meantime, you can you test the PR #31 we will wait for the merge of QEMU8 to merge that one.

**Comment by aurelf** [comment]
Closed by #42
