### ISSUE TITLE
[Question] system-mode multiple CPUs support

### ISSUE THREAD

**Issue by now4yreal** [eurecom-s3/symqemu#46]
Dear maintainers:

Does symqemu x86 system mode support multiple processes and multiple CPUs? If not, do you have plans to implement this feature?

**Comment by aurelf** [comment]
Hi, 
We have some intenal system mode prototype, we are planning to merge this at some point. But it's not yet there. 
System mode will support running multiprocess as it emulates a full VM. But I'm not sure what is the status of the prototype for: 
- analysis across processes (passing constraints between processes)
- multicore support.
Maybe @rmalmain could complete if needed. 
What are you trying to do ?

**Comment by now4yreal** [comment]
Thank you for your prompt reply. I'm just interested in symqemu and I will dive into the source code later.
