### ISSUE TITLE
Can't build arm-linux-user in the lastest symqemu

### ISSUE THREAD

**Issue by manba-bryant** [eurecom-s3/symqemu#53]
Sorry to bother you again.
below the picture is the error of my situation:
![image](https://github.com/eurecom-s3/symqemu/assets/90821399/f4173d1f-3e48-404e-9952-a1a0a88a323d)
![image](https://github.com/eurecom-s3/symqemu/assets/90821399/e7c52b02-1a26-4979-8452-3649fa05b420)
I would't meet this error while building x86_64-linux-user .
What can i do to resolve this question? Thanks a lot!

**Comment by sebastianpoeplau** [comment]
This should be fixed with #54; feel free to reopen the issue if it isn't.

**Comment by ping-anban** [comment]
> This should be fixed with #54; feel free to reopen the issue if it isn't.
yes，it works。
Another question ,the problem with arm-linux-user in this version as below does it resolved?
![image](https://github.com/eurecom-s3/symqemu/assets/150405284/f16362e8-7355-4344-aea0-13a5cabacc01)

**Comment by manba-bryant** [comment]
> This should be fixed with #54; feel free to reopen the issue if it isn't.
yes ,it works。Thanks a lot.
Another question ,the problem with arm-linux-user in this version as below does it resolved?
![image](https://github.com/eurecom-s3/symqemu/assets/90821399/bbc159e8-5c3f-4b1a-85dc-ae5ffbddb7a3)
Looking forward your response

**Comment by aurelf** [comment]
It should be working (we just merged qemu 9). Open an issue if it doesn't, or better a PR with a test case.
